
name: vkdr-install
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: veecode-platform/vkdr-install
  index_document: vkdr-install.sh
  name: vkdr-install
  source_dir: /
