
name: vkpr-install
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: vertigobr/vkpr-install
  index_document: "vkpr-install.sh"
  routes:
  - path: /
  source_dir: /
  name: vkpr-install
